### ISSUE TITLE
README info

### ISSUE THREAD

**Issue by danielsz** [jalehman/ring-transit#11]
Hi, 

Here's a scenario: 
User has not worked with transit yet, and is "shopping" for ring middleware, and immediately sees two likely candidates: ring-transit and [ring-middleware-format](https://github.com/ngrunwald/ring-middleware-format). User is confused. 

Here's another scenario:
User uses Liberator and is "shopping" for transit middleware, and immediately notices that there is a thing called [liberator-transit](https://github.com/sattvik/liberator-transit) that seems to fit the bill, although it operates higher on the abstraction stack than ring middleware. Again, user is confused. 

Clearing up the confusion in the README would be awesome. 

Thanks!

**Comment by harold** [comment]
@danielsz - do you know the difference? That is do `ring-transit` and `ring-middleware-format` solve the same, or different, problems?

**Comment by danielsz** [comment]
Awesome. Thanks for the clarification, @jalehman 

@harold Sorry, I missed your question. But we've got our answers now :-)

I've been using ring-middleware-format for all my serialization needs (a couple of years now)

**Comment by jalehman** [comment]
Sure thing -- sorry about the delay!
