### ISSUE TITLE
Nested maps.

### ISSUE THREAD

**Issue by danielsz** [jalehman/ring-transit#5]
Hi, 

I'm sending nested Clojure maps over the wire with clj-http (transit+json is set as the content-type). 
On the other side, where ring-transit is used, the maps are transformed into json arrays. 

In other words, this is what is happening:

This goes in:
```clojure
{:twitter {:access-token-response {:user_id "123577893"}}}
```
This goes out:
```clojure
:transit-param {"twitter[access-token-response][user_id]"
		 "123577893"}. 
```

What I would like to achieve: 

This goes in:

```clojure
{:twitter {:access-token-response {:user_id "123577893"}}}
````

This goes out:

```clojure
:transit-param {:twitter {:access-token-response {:user_id "123577893"}}}
```

Or in other words, how do I serialize/deserialize nested Clojure maps?

Thank you in advance.

**Comment by jalehman** [comment]
@danielsz Sorry for the very late response!

I've been unable to find any issue with how this library serializes/deserializes nested Clojure maps into/from Transit.

If you were sending a nested map from `clj-http` to a server running `ring-transit`, is it possible that `clj-http` was not correctly serializing the Clojure map to transit?

**Comment by danielsz** [comment]
Hi @jalehman, 

It is possible, definitely. (But it doesn't matter anymore). Thank you!
