### ISSUE TITLE
Detect when transit body is already read

### ISSUE THREAD

**Issue by aroemers** [jalehman/ring-transit#8]
Many ring middlewares detect whether they have already performed their transformation. Maybe this would be a nice addition to ring-transit as well? 

I accidentally added the wrap-transit-body twice to a handler, and the second one could not parse the body (obviously).<sup>1</sup>

Also, it would nice to move the logic in the various `wrap-` functions into functions like `transit-request-body`, `transit-request-params` and `transit-response`, just like many standard ring middlewares do, for example the [session](https://github.com/ring-clojure/ring/blob/master/ring-core/src/ring/middleware/session.clj) middleware.

Thoughts?

<sup>1</sup> it took some REPL redefinitions to figure out why, see issue #7.

**Comment by jalehman** [comment]
@aroemers Sorry for the late response!

Added something to solve this [here](https://github.com/jalehman/ring-transit/blob/master/src/ring/middleware/transit.clj#L50). Did pull `transit-response` out, but went a different direction with the other two. If you've got a better implementation in mind I'd be happy to merge it!
